### ISSUE TITLE
Fermipy 0.20.0 gtanalysis runtime error

### ISSUE THREAD

**Issue by jleagle94** [fermiPy/fermipy#365]
Hi all

I recently updated to Fermitools 2.0* on my MacOS Catalina (and the Docker fermibottle container).
Both systems are running Conda 4.8.* and have fermipy 0.20.0 and they both are giving me the same error when reading in a configuration file to fermipy. The following error is ran through Docker but, same thing occurs on my Mac local.
I activate my python3 environment and then my fermitools environment. 
```
(fermi) [fermi@d77a31220556 ~]$ conda list fermi
# packages in environment at /opt/anaconda/envs/fermi:
#
# Name                    Version                   Build  Channel
fermipy                   0.20.0           py37h7b7c402_0    conda-forge
fermitools                2.0.0                hf484d3e_0    fermi
fermitools-data           0.18                          0    fermi
fermitools-dependencies   2.0.0                         0    fermi
```
 In this particular set up, I'm using an old config file that I know works fine:
```
(fermi) [fermi@d77a31220556 old_pwn_analysis_msh1556]$ python
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fermipy.gtanalysis import GTAnalysis
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-o9b6p8u9 because the default path (/home/fermi/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
>>> gta = GTAnalysis('config.yaml',logging={'verbosity' : 3})
/opt/anaconda/envs/fermi/lib/python3.7/site-packages/fermipy/config.py:213: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict = yaml.load(open(config))
2020-09-29 22:01:03 INFO    GTAnalysis.__init__(): 
--------------------------------------------------------------------------------
fermipy version 0.20.0 
ScienceTools version 2.0.0
/opt/anaconda/envs/fermi/lib/python3.7/site-packages/fermipy/model_utils.py:59: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  get_function_spec.fndict = yaml.load(open(modelfile))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 356, in __init__
    comp = self._create_component(cfg, loglevel=self.loglevel)
  File "/opt/anaconda/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 942, in _create_component
    for k in cfg.keys():
RuntimeError: dictionary changed size during iteration
```

This appears to be just some kind of python error. Help would be greatly appreciated :)

**Comment by cameronrulten** [comment]
Fermipy needs to be updated to work with newer versions of pyaml (see Issue #363) which looks like the start of your problems. Until there is a new fermipy release you'll probably have to revert to a python2 version of the fermitools unless you can get it working in a Conda environment with an older version of pyaml <v5.1 installed.

**Comment by nuk34** [comment]
I have the same error (same setup). I don't think that it comes from yaml, this is just a warning. I think the problem is in
```
        for k in cfg.keys():
            if not k in GTBinnedAnalysis.defaults:
                cfg.pop(k)
```
where you delete keys while looping over it (apparently there is a change how things a handled in python3). It does work with
```
       for k in cfg.copy().keys():
```
But then I get an error when ```coordsys``` is passed to ```WcsGeom```. This argument does not exist in gammapy 0.17.

**Comment by jleagle94** [comment]
This is what I was thinking, too. Though I am not totally sure. I tried your workaround and I get the same error now as you!

`TypeError: create() got an unexpected keyword argument 'coordsys'`

**Comment by eacharles** [comment]
The main issue here is that the current version of fermipy hasn’t been updated to support python 3 yet.

I will make releasing a version that supports python 3 a top priority.  It was difficult to test it without a python3 fermitools release.

-e

**Comment by jleagle94** [comment]
Darn. Didn't realize that. Will work with Fermitools 1 in python 2.7 for now then.

**Comment by eacharles** [comment]
I’m very close to having it working.  Mostly I just need to package it up for conda, which requires some work in making sure it gets the right version of the fermitools so that the unit tests actually run.

-e

**Comment by cameronrulten** [comment]
> I have the same error (same setup). I don't think that it comes from yaml, this is just a warning. I think the problem is in
> 
> ```
>         for k in cfg.keys():
>             if not k in GTBinnedAnalysis.defaults:
>                 cfg.pop(k)
> ```
> 
> where you delete keys while looping over it (apparently there is a change how things a handled in python3). It does work with
> 
> ```
>        for k in cfg.copy().keys():
> ```
> 
> But then I get an error when `coordsys` is passed to `WcsGeom`. This argument does not exist in gammapy 0.17.

Hi Nukri 👋, you're right I misread the error output.

**Comment by mealworm** [comment]
Hi all,
fermipy 1.0.0 is still giving the same error:

gta.setup()
2020-10-12 08:13:19 INFO    GTAnalysis.setup(): Running setup.
2020-10-12 08:13:19 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
2020-10-12 08:13:19 INFO    GTBinnedAnalysis.run_gtapp(): Running gtselect.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-1e27b2b06e27> in <module>
----> 1 gta.setup()

/srv/conda/envs/notebook/lib/python3.7/site-packages/fermipy/gtanalysis.py in setup(self, init_sources, overwrite, **kwargs)
   1080         # Run setup for each component
   1081         for i, c in enumerate(self.components):
-> 1082             c.setup(overwrite=overwrite)
   1083 
   1084         # Create likelihood

/srv/conda/envs/notebook/lib/python3.7/site-packages/fermipy/gtanalysis.py in setup(self, overwrite, **kwargs)
   5110         # Run data selection
   5111         if not use_external_srcmap:
-> 5112             self._select_data(overwrite=overwrite, **kwargs)
   5113 
   5114         # Create LT Cube

/srv/conda/envs/notebook/lib/python3.7/site-packages/fermipy/gtanalysis.py in _select_data(self, overwrite, **kwargs)
   5192 
   5193         run_gtapp('gtselect', self.logger, kw_gtselect,
-> 5194                   loglevel=loglevel)
   5195         if self.config['selection']['roicut'] == 'yes' or \
   5196                 self.config['selection']['filter'] is not None:

/srv/conda/envs/notebook/lib/python3.7/site-packages/fermipy/gtanalysis.py in run_gtapp(appname, logger, kw, **kwargs)
    199     logger.log(loglevel, 'Running %s.', appname)
    200     t0 = time.time()
--> 201     filter_dict(kw, None)
    202     kw = utils.unicode_to_str(kw)
    203     gtapp = GtApp.GtApp(str(appname))

/srv/conda/envs/notebook/lib/python3.7/site-packages/fermipy/gtanalysis.py in filter_dict(d, val)
    225 
    226 def filter_dict(d, val):
--> 227     for k, v in d.items():
    228         if v == val:
    229             del d[k]

RuntimeError: dictionary changed size during iteration

**Comment by jleagle94** [comment]
Closing since the issue was using Fermipy 0.20 with Fermitools 2.0.0. Users need Fermipy 1.0.0 to work with Fermitools 2.0.0.
